# Server configuration
server.port=8080

# View resolver
spring.mvc.view.prefix=/WEB-INF/view/
spring.mvc.view.suffix=.jsp

# Database configuration
spring.datasource.url=jdbc:mysql://localhost:3306/rohitdb
spring.datasource.username=root
spring.datasource.password=rohit

# Hibernate settings
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
